// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm_ncIPSVQ_gx5M3zYzcm21JTxMYAd0tg',
    appId: '1:338903811682:web:5087a7c8517e7438c9333b',
    messagingSenderId: '338903811682',
    projectId: 'vlack-a0e92',
    authDomain: 'vlack-a0e92.firebaseapp.com',
    storageBucket: 'vlack-a0e92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLsBRMzRuasrARowrSecUU4AFr9yopLAY',
    appId: '1:338903811682:android:42775f62576e9146c9333b',
    messagingSenderId: '338903811682',
    projectId: 'vlack-a0e92',
    storageBucket: 'vlack-a0e92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfq04pu-qjRwlB1_tjS7-xvWsDo60JNok',
    appId: '1:338903811682:ios:649906801772f83ac9333b',
    messagingSenderId: '338903811682',
    projectId: 'vlack-a0e92',
    storageBucket: 'vlack-a0e92.appspot.com',
    iosBundleId: 'com.example.blackner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfq04pu-qjRwlB1_tjS7-xvWsDo60JNok',
    appId: '1:338903811682:ios:75262e9c70c13d34c9333b',
    messagingSenderId: '338903811682',
    projectId: 'vlack-a0e92',
    storageBucket: 'vlack-a0e92.appspot.com',
    iosBundleId: 'com.example.blackner.RunnerTests',
  );
}
